package mizchi:brotli;

interface decompress {
  decompress: func(data: list<u8>) -> result<list<u8>, string>;
}

interface compress {
  compress: func(data: list<u8>) -> list<u8>;
  compress-with-quality: func(data: list<u8>, quality: u32) -> list<u8>;
}

world brotli {
  export decompress;
  export compress;
}
